# Generated by Django 3.2.5 on 2021-08-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionfile',
            name='file_type',
            field=models.CharField(default='image', max_length=255),
            preserve_default=False,
        ),
    ]
