# Generated by Django 3.2.5 on 2021-08-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='one.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
